import { jsxs, Fragment, jsx } from 'atomico/jsx-runtime';
import { Markdown } from './markdown.js';
import { Preview } from './preview.js';
import { Code } from './code.js';
import { Editor } from './editor.js';
import 'atomico';
import '@atomico/hooks/use-css-light-dom';
import './hero.js';
import './tokens.js';
import './button.js';
import './button/group.js';
import '@atomico/hooks/use-slot';
import './author.js';
import '@atomico/hooks/use-render';
import 'highlight.js';
import './scroll.js';
import 'scrollable-component';
import '@atomico/hooks/use-copy';

const meta = {
  title: "Stories",
  description: /* @__PURE__ */ jsxs(Fragment, { children: [
    "Markdown with ",
    /* @__PURE__ */ jsx("b", { children: "superpowers" })
  ] }),
  author: "uppercod"
};

const _7b17cc992fd7a83990716841d0a67ef1 = /* @__PURE__ */ jsxs(Fragment, { children: [
  /* @__PURE__ */ jsxs("p", { children: [
    /* @__PURE__ */ jsx("strong", { children: "@atomico/storie" }),
    " aims to provide a code demo experience using Markdown + Atomico. For example, if you add the preview declaration to your Markdown code block, it will be rendered by Atomico, allowing you to have a preview of the code written within your Markdown. Here's an example of the declaration:"
  ] }),
  /* @__PURE__ */ jsx(Code, { type: "markdown", value: "%60%60%60tsx%20preview%20focus%0Aimport%20%7B%20Author%20%7D%20from%20%22./author%22;%0A%0Aexport%20default%20%3CButton%3EExample%3C/Button%3E;%0A%60%60%60" }),
  /* @__PURE__ */ jsx("p", { children: "Result of the previous declaration:" }),
  /* @__PURE__ */ jsxs(Editor, { text: "import%20%7B%20Button%20%7D%20from%20%22./button%22;%0A%0Aexport%20default%20%3CButton%3EExample%3C/Button%3E;", children: [
    /* @__PURE__ */ jsx(Preview, { label: "Preview", focus: true, load: () => import('./chunks/129a69833acee3cacbe79914b1a97cba.js') }),
    /* @__PURE__ */ jsx(Code, { label: "Code", type: "tsx preview focus", value: "import%20%7B%20Button%20%7D%20from%20%22./button%22;%0A%0Aexport%20default%20%3CButton%3EExample%3C/Button%3E;" })
  ] }),
  /* @__PURE__ */ jsx("p", { children: "This is really simple to use, and you can customize each type of Markdown block and replace it with webcomponents." }),
  /* @__PURE__ */ jsx("hr", {}),
  /* @__PURE__ */ jsx("h2", { children: "Markdown component" }),
  /* @__PURE__ */ jsxs("p", { children: [
    "The ",
    /* @__PURE__ */ jsx("code", { children: "<Markdown/>" }),
    " component allows rendering content generated by the *.md modules generated by @atomico/vite."
  ] }),
  /* @__PURE__ */ jsx("h1", { children: "title 1" }),
  /* @__PURE__ */ jsx("h2", { children: "title 2" }),
  /* @__PURE__ */ jsx("h3", { children: "title 3" }),
  /* @__PURE__ */ jsx("h4", { children: "title 4" }),
  /* @__PURE__ */ jsx("h5", { children: "title 5" }),
  /* @__PURE__ */ jsx("p", { children: "Lorem ipsum dolor sit amet consectetur adipiscing elit blandit felis posuere, tincidunt donec iaculis libero bibendum vitae penatibus quis. Nibh est senectus nulla mus lectus risus porttitor, duis commodo conubia scelerisque et etiam magna." }),
  /* @__PURE__ */ jsx("blockquote", { children: /* @__PURE__ */ jsxs("p", { children: [
    "Lorem ipsum dolor sit amet consectetur adipiscing elit blandit felis posuere, tincidunt ",
    /* @__PURE__ */ jsx("code", { children: "donec iaculis libero" }),
    " bibendum vitae penatibus quis."
  ] }) }),
  /* @__PURE__ */ jsxs("ol", { children: [
    /* @__PURE__ */ jsx("li", { children: "Lorem ipsum dolor sit amet consectetur adipiscing elit blandit" }),
    /* @__PURE__ */ jsx("li", { children: "felis posuere, tincidunt donec iaculis libero bibendum vitae" }),
    /* @__PURE__ */ jsxs("li", { children: [
      "penatibus quis. Nibh est senectus nulla mus lectus risus porttitor,",
      /* @__PURE__ */ jsxs("ol", { children: [
        /* @__PURE__ */ jsx("li", { children: "duis commodo conubia scelerisque et etiam magna." }),
        /* @__PURE__ */ jsx("li", { children: "duis commodo conubia scelerisque et etiam magna." })
      ] })
    ] })
  ] }),
  /* @__PURE__ */ jsx("p", { children: /* @__PURE__ */ jsx("img", { src: "https://images.unsplash.com/photo-1698399134573-cf1754493ead?auto=format&fit=crop&q=80&w=2574&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", alt: "image" }) })
] });

const readme = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  default: _7b17cc992fd7a83990716841d0a67ef1,
  meta
}, Symbol.toStringTag, { value: 'Module' }));

const example = /* @__PURE__ */ jsx("host", { children: /* @__PURE__ */ jsx(Markdown, { style: "max-width: 980px", module: readme }) });

export { example as default };
