import { css } from 'atomico';

const tokensColor = css`:host{--color-primary:var(--stories--color-primary);--color-secondary:var(--stories--color-secondary);--color-contrast:var(--stories--color-contrast);--color-neutral:var(--stories--color-neutral);--color-container:var(--stories--color-container);--color-frame:var(--stories--color-frame);}`;
const tokensButton = css`:host{--radius:var(--stories--button-radius);--size:var(--stories--button-size);--padding:var(--stories--button-padding);--font-size:var(--stories--button-font-size);--group-color:var(--stories--button-group-color);--group-border:var(--stories--button-group-border);--color-container:var(--stories--button-color-container);--color-text:var(--stories--button-color-text);}:host([checked]){--color-container:var(--stories--button-color-container--is-checked);--color-text:var(--stories--button-color-text--is-checked);}:host([small]){--radius:var(--stories--button-radius--is-small);--size:var(--stories--button-size--is-small);--padding:var(--stories--button-padding--is-small);--font-size:var(--stories--button-font-size--is-small);}:host([icon]){--padding:var(--stories--button-padding--is-icon);}:host([appearance=tab]){--color-container:var(--stories--button-color-container--appearance-is-tab);--color-text:var(--stories--button-color-text--appearance-is-tab);}:host([appearance=tab][checked]){--color-container:var(--stories--button-color-container--appearance-is-tab--is-checked);--color-text:var(--stories--button-color-text--appearance-is-tab--is-checked);}`;
const tokensCard = css`:host{--radius:var(--stories--card-radius);--padding:var(--stories--card-padding);--border:1px solid var(--stories--card-color-border);--gap:var(--stories--card-gap);--color-contrast:var(--stories--card-color-contrast);--color-border:var(--stories--card-color-border);}`;
const tokensCode = css`:host{--font-size:var(--stories--code-font-size);--font-height:var(--stories--code-font-height);}`;
const tokensEditor = css`:host{--color-background:var(--color-container);--border:var(--stories--editor-border-size) solid var(--stories--color-frame);--border-size:var(--stories--editor-border-size);--editor-background--slot-is-role:var(--stories--editor-background--slot-is-role);--editor-radius--slot-is-role:var(--stories--editor-radius--slot-is-role);--editor-border--slot-is-role:var(--stories--editor-border--slot-is-role);}::slotted([role=preview]){--background:var(--editor-background--slot-is-role);}::slotted([role=code]){--radius:var(--editor-radius--slot-is-role);--border:var(--editor-border--slot-is-role);}`;
const tokensHero = css`:host{--color-dot:var(--stories--hero-color-dot);--color-gradient:var(--stories--hero-color-gradient);--hero-color-radius--any-slot:var(--stories--hero-color-radius--any-slot);}::slotted(*){--color-radius:var(--hero-color-radius--any-slot);}`;
const tokensScroll = css`:host{--width:var(--stories--scroll-width);}`;
const tokens = css`:root{--stories--color-primary:#000;--stories--color-secondary:#A1A1A9;--stories--color-contrast:#fff;--stories--color-neutral:#D0D9D8;--stories--color-container:#fff;--stories--color-frame:#E1E1E9;--stories--card-radius:1rem;--stories--card-padding:0.625rem;--stories--card-border:1px solid var(--stories--card-color-border);--stories--card-gap:1rem;--stories--card-color-contrast:rgba(0,0,0,.025);--stories--card-color-border:rgba(0,0,0,.1);--stories--code-font-size:1rem;--stories--code-font-height:1.2;--stories--editor-color-background:var(--stories--color-container);--stories--editor-border:var(--stories--editor-border-size) solid var(--stories--color-frame);--stories--editor-border-size:1px;--stories--editor-background--slot-is-role:transparent;--stories--editor-radius--slot-is-role:0 0 var(--stories--card-radius) var(--stories--card-radius);--stories--editor-border--slot-is-role:none;--stories--hero-color-dot:rgba(0,0,0,.25);--stories--hero-color-gradient:transparent;--stories--hero-color-radius--any-slot:0px;--stories--button-radius:1.25rem;--stories--button-size:2rem;--stories--button-padding:0 1.25rem;--stories--button-font-size:0.875rem;--stories--button-group-color:rgba(0,0,0,.05);--stories--button-group-border:none;--stories--button-color-container:rgba(0,0,0,.1);--stories--button-color-text:black;--stories--button-color-container--is-checked:black;--stories--button-color-text--is-checked:white;--stories--button-radius--is-small:0.875rem;--stories--button-size--is-small:28px;--stories--button-padding--is-small:0 0.625rem;--stories--button-font-size--is-small:0.75rem;--stories--button-padding--is-icon:0;--stories--button-color-container--appearance-is-tab:transparent;--stories--button-color-text--appearance-is-tab:black;--stories--button-color-container--appearance-is-tab--is-checked:black;--stories--button-color-text--appearance-is-tab--is-checked:white;--stories--scroll-width:.5rem;}`;
document.adoptedStyleSheets = [tokens, ...document.adoptedStyleSheets];

export { tokens, tokensButton, tokensCard, tokensCode, tokensColor, tokensEditor, tokensHero, tokensScroll };
